title: The SILE Typesetter
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
baseurl: ""
paginate: 5
paginate_path: "blog/page:num"
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-mentions
exclude:
  - '*.toc'
  - public
  - vendor
  - Makefile*
  - tags
  - fontconfig.conf
  - '*.nix'
permalink: /:categories/:year/:month/:slug
