base_url = "https://sile-typesetter.org"

title = "The SILE Typesetter"

compile_sass = false
build_search_index = false

generate_feed = true
feed_filename = "feed.xml"

[markdown]
highlight_code = true

[extra]
