base_url = "/"

title = "The SILE Typesetter"

compile_sass = true
build_search_index = false

generate_feeds = true
feed_filenames = [ "feed.xml" ]

[slugify]
paths = "safe"
taxonomies = "safe"
anchors = "safe"

[markdown]
highlight_code = true

[extra]
