name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  gh-pages:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/jekyll/jekyll/issues/7591
      - name: Setup Jekyll
        run: |
          docker pull jekyll/builder:latest
          mkdir .jekyll-cache

      - name: Build the site
        run: |
          export JEKYLL="docker run -v "$(pwd)":/srv/jekyll jekyll/builder:latest jekyll"
          make site

      - name: Inject CNAME
        if: ${{ github.repository == 'sile-typesetter/sile-typesetter.github.io' }}
        run: |
          make public/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
