name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  gh-pages:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    container:
      image: docker://nixos/nix
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup build dependencies
        run: |
          nix-channel --add https://nixos.org/channels/nixpkgs-unstable
          nix-channel --update

      - name: Generate static site
        run: |
          nix-shell --run make

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
