name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  gh-pages:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install project dependencies
        run: |
          nix-shell --run true

      - name: Generate example pdfs
        run: |
          nix-shell --run 'make examples'

      - name: Generate static site pages
        run: |
          nix-shell --run 'make jekyll'

      - name: Inject CNAME
        if: ${{ github.repository == 'sile-typesetter/sile-typesetter.github.io' }}
        run: |
          nix-shell --run 'make public/CNAME'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
